#!/bin/zsh

# Make a list of all the files except "install"
typeset -A files_hash
all_files=(*)
files_hash=(${=${(j: 1 :)all_files}} 1)
unset "files_hash[install]"
unset "files_hash[README]"
files=(${(k)files_hash})

print "Files to install: ${(j:, :)files}"

backupdir=~/.dotbackup/`date "+%Y%m%dT%H%M%S"`

print "Backing up files to $backupdir"

if [[ ! -e $backupdir ]] then
  mkdir -p $backupdir
fi

cp -R ${files/#/~/.} $backupdir

print "Replacing files"

for f in $files; do
  target=${f/#/~/.}
  rm -fr $target
  cp -R $f $target
done
