#! /bin/zsh

export SHELL=/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="walter@carezone.com"
export FULLNAME="Walter Smith"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

# export IRCNICK=wrs
# export IRCNAME=${FULLNAME}
# export IRCSERVER=irc.irc.irc
# export IRC_SERVERS_FILE="$HOME/.irc-serv"

export MANWIDTH=80
export EDITOR='mvim -f -c "au VimLeave * !open -a iTerm"'
export VISUAL=$EDITOR
export BUNDLER_EDITOR=mvim

export CLICOLOR=1
#export CCACHE_DIR=$HOME/.ccache

# export INPUTRC="~/.inputrc"
# export MAIL="${HOME}/mail/inbox"

# export RLWRAP_HOME=~/.cache/rlwrap/
# export GTK_IM_MODULE=xim

export LC_MESSAGES=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if [ -d /opt/local/bin ]; then
        PATH="/opt/local/bin:/opt/local/sbin:${PATH}"
        export MANPATH="/opt/local/man:${MANPATH}"
fi

if [ -d /usr/local/mysql ]; then
        PATH="/usr/local/mysql/bin:${PATH}"
        export MANPATH="/usr/local/mysql/man:${MANPATH}"
fi

if [ -d /opt/local/lib/postgresql84/bin ]; then
        PATH="/opt/local/lib/postgresql84/bin:${PATH}"
fi

if [ -d /usr/local/share/python ]; then
        PATH="/usr/local/share/python:${PATH}"
fi

if [ -d /usr/local/bin ]; then
        PATH="/usr/local/bin:${PATH}"
        export MANPATH="/usr/local/man:${MANPATH}"
fi

if [ -d /Library/PostgreSQL/8.4/bin ]; then
        PATH="/Library/PostgreSQL/8.4/bin:${PATH}"
fi

export EC2_HOME=~/aws/ec2-api-tools
PATH="$EC2_HOME/bin:${PATH}"

export AWS_ELB_HOME=~/aws/elb-tools
PATH="$AWS_ELB_HOME/bin:${PATH}"

export ANDROID_HOME="/Applications/Android Studio.app/sdk"
PATH="${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${PATH}"

PATH="${HOME}/bin:${PATH}"

# Java for Mac OS X

export JAVA_HOME=/Library/Java/Home

# less options
LESS=aFmqRX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
# CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"

# Homebrew node.js libs
export NODE_PATH=/usr/local/lib/node

# Fixes JSLint in MacVIM
export JS_CMD=node

# Go!
export GOROOT=/usr/local/go
export GOPATH=~/src/go
PATH="${GOPATH}/bin:${GOROOT}/bin:$PATH"

export PATH
