#!/bin/zsh

autoload zmv
alias mmv='noglob zmv -W'

# if ( which sudo >/dev/null 2>/dev/null ) ; then
#         alias su='export XAUTHORITY=${HOME}/.Xauthority ; sudo -s'
#         alias sudo='export XAUTHORITY=${HOME}/.Xauthority ; sudo'
# fi

alias du="du -hcs"
alias df="df -h"

alias la="ls -a"
alias ll="ls -l"
alias lla="ls -la"
alias lal="ls -la"

# alias rm='rm -i'

# cvi () {
#     vim -O ${${1%.[hc]}%.}.{h,c}
# }
# 
# xvi () {
#     vim -O ${${${1%.h}%.cpp}%.}.{h,cpp}
# }

wt() { 
        while true ; do ( $@ ) ; sleep 1 ; clear ; done
}

function bdiff() { diff "$1" "$2" || diff <(hex "$1") <(hex "$2") ; }

# tohtml() {
#         if test -z $1 ; then
#                 echo "tohtml <file>" >&2
#                 return 1
#         fi
#         vim -e +:TOhtml +w +qa $1
# }

yyyymmdd () { date +%Y%m%d ; }
yyyymmdd-hhmmss () { date +%Y%m%d-%H%M%S ; }
alias ymd=yyyymmdd
alias ymd-hms=yyyymmdd-hhmmss

# function vman() { vim -c ":RMan ${*}" ; }
# function vimgrep () { tmp="$@" ; vim -c "vimgrep $tmp" ; }
# 
# function xpwd () { echo $PWD | xclip -i ; xclip -o ; }
# function xcd () { cd `xclip -o` ; }

function sum() { SUM=0; while read NUM; do SUM=$(($SUM+$NUM)); done; echo $SUM; }

# cdd x will do cd ../x
alias cdd="cd `basename \`pwd\``"

#alias vnice="ionice -n7 nice -n20"
vnice() {
        if test -z "$1" ; then
                echo "vnice [ <pid> | <program> ]" >&2
                return 1
        elif ( echo "$1" | grep -q '^[0-9]*$' ) ; then
                ionice -n7 -p $1
                renice 20 $1
        else
                ionice -n7 nice -n20 $@
        fi
}

alias g=git
function gstart() { git checkout -b "$1" master }
function gfinish() { git checkout "$1" && git rebase master && git checkout master && git merge "$1" && git branch -d "$1" }
function gpull() { oldrev=`git rev-parse origin/master`; git pull && git log --oneline $oldrev..origin/master }

function hr() { echo $(tput cuu1)$fg[blue]$(printf '─%.0s' $(seq $COLUMNS)) }

function sst { ssh -t $1.czops.net 'cd /srv/careful/current 2> /dev/null; sudo su deploy' }

function e { emacsclient -n -c $*}
