#!/bin/zsh

# http://zshwiki.org/home/examples/zleiab

setopt extendedglob

typeset -Ag abbreviations
abbreviations=(
  ",l"    "| less"
  ",g"    "| grep"
  ",h"    "| head"
  ",t"    "| tail"
  ",s"    "| sort"
  ",m"    "| mate"
  ",w"    "| wc"
  ",x"    "| xargs"
)

magic-abbrev-expand() {
    local MATCH
    LBUFFER=${LBUFFER%%(#m)[,_a-zA-Z0-9]#}
    LBUFFER+=${abbreviations[$MATCH]:-$MATCH}
    zle self-insert
}

no-magic-abbrev-expand() {
  LBUFFER+=' '
}

zle -N magic-abbrev-expand
zle -N no-magic-abbrev-expand
bindkey " " magic-abbrev-expand
bindkey "^x " no-magic-abbrev-expand
